---
- name: Run default dependencie installation procress
  include_tasks: install_default.yml
  tags:
    - dehydrated
    - packages

- name: Make sure cronie is running
  service:
    name: cronie
    state: started
    enabled: true
  tags:
    - dehydrated
