---
- name: Ensure all dehydrated dependencies are installed
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - openssl
    - curl
    - sed
    - grep
    - coreutils
  tags:
    - apt
    - dehydrated
