---
- name: Ensure all dehydrated dependencies are installed
  pacman:
    pkg: "{{item}}"
    state: present
  with_items:
    - openssl
    - curl
    - sed
    - grep
    - coreutils
  tags:
    - dehydrated
