---
- name: Ensure all dehydrated dependencies are installed
  pacman:
    pkg: "{{item}}"
    state: present
  with_items:
    - openssl
    - curl
    - sed
    - grep
    - coreutils
    - cronie
  tags:
    - dehydrated

- name: Make sure cronie is running
  service:
    name: cronie
    state: started
    enabled: true
  tags:
    - dehydrated
