---
- name: Gather OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version}}.yml"
        - "{{ ansible_distribution|lower }}.yml"
        - "{{ ansible_os_family|lower }}.yml"
      skip: true
  tags:
    - dehydrated
    - vars

- name: Ensure that the letsencrypt challenge and letsencrypt cert directory exists
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: root
  with_items:
    - "{{ dehydrated_acme_challenge_path }}"
    - "{{ dehydrated_cert_path }}"
  tags:
    - dehydrated

- name: include install tasks
  include_tasks: "{{ item }}"
  with_first_found:
    - "install_{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version }}.yml"
    - "install_{{ ansible_distribution|lower }}.yml"
    - "install_{{ ansible_os_family|lower }}.yml"
    - "install_default.yml"
  tags:
    - dehydrated
    - packages

- name: Ensure that the dehydrated configuration exists
  template:
    src: dehydrated.conf
    dest: "{{ dehydrated_cert_path }}/dehydrated.conf"
  tags:
    - ssl

- name: Ensure that the dehydrated hooks file exists
  template:
    src: hooks.sh
    dest: "{{ dehydrated_cert_path }}/hooks.sh"
    mode: 0750
    owner: root
  tags:
    - dehydrated

- name: Ensure that the letsencrypt domain list file exists
  file:
    path: "{{ dehydrated_cert_path }}/domains.txt"
    state: touch
  tags:
    - dehydrated

- name: Build the letsencrypt domain list
  template:
    src: domains.txt.j2
    dest: /etc/ssl/letsencrypt/domains.txt
  tags:
    - dehydrated

- name: Download the dehydrated shell script
  get_url:
    url: "{{ dehydrated_binary }}"
    dest: /etc/ssl/letsencrypt/dehydrated
    mode: 0700
    sha256sum: "{{ dehydrated_binary_sha256 }}"
  tags:
    - dehydrated

- name: Accept the Terms of Service if nessesary
  command: ./dehydrated --register --accept-terms -f {{ dehydrated_cert_path }}/dehydrated.conf
  args:
    chdir: "{{ dehydrated_cert_path }}"
  tags:
    - dehydrated

- name: Execute dehydrated shell script
  command: ./dehydrated -c --hook {{ dehydrated_cert_path }}/hooks.sh -f {{ dehydrated_cert_path }}/dehydrated.conf
  args:
    chdir: "{{ dehydrated_cert_path }}"
  tags:
    - dehydrated

- name: Add letsencrypt cronjob
  cron:
    name: letsencrypt
    hour: 7
    minute: 0
    day: "*/3"
    job: "{{ dehydrated_cert_path }}/dehydrated -c --hook {{ dehydrated_cert_path }}/hooks.sh -f {{ dehydrated_cert_path }}/dehydrated.conf"
  tags:
    - dehydrated
